### ISSUE TITLE
Implement archetype action: Draconic Knight - Fly / Land

### ISSUE THREAD

**Issue by Christian-Toney** [EveryoneDestroysTheWorld/game#101]
# Dependencies
- [x] #98 

# Completion criteria
- [x] #218
- [x] Let the player soar after they double tap the jump button. 
- [x] Ensure the player doesn't fall while they're not moving.
- [x] Drain a reasonable amount of stamina while active.
- [x] Double tap the jump button to disable the action.

**Comment by zriku1** [comment]
finished in hatibranch
occasionally bugs when spamming jump, will fix soon
