### ISSUE TITLE
Implement archetype action: Draconic Knight - Beast Slash

### ISSUE THREAD

**Issue by Christian-Toney** [EveryoneDestroysTheWorld/game#102]
# Dependencies
- [x] DemoDemons/design#169

# Related design entries
* https://github.com/EveryoneDestroysTheWorld/design/blob/main/inventory/archetypes/draconic-knight.md

# Completion criteria
- [x] Let the player swipe on every primary action button click.
- [x] Reasonably reduce stamina.
- [x] Let the player charge the swipe by holding the button.
- [x] Make sure this is only works while grounded, not flying.

**Comment by zriku1** [comment]
attack added, charge attack WIP

**Comment by zriku1** [comment]
finished
